services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dms-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "DmsStrong123P"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata:
